import {TYPES,makePoints,legalReason,replay,handWinner,angles} from './engine.mjs';
const $=id=>document.getElementById(id),colors=['#356cdb','#d97140'],handNames=['바위','보','가위'],handSymbols=['✊','✋','✌️'];
let config=null,remote=null,connecting=null,room=null,roomCode='',model=null,slot=0,demo=false,demoSlot=0,selected=[],busy=false,network=false,unsub=null,unsubPresence=null,stopConnected=null,presence={},acceptVersion=0,advancing=false,toastTimer,effectTimer,detailsIndex=null,lastEffectCount=0;
const prefs={get(k){try{return localStorage.getItem('triangle:'+k)}catch{return null}},set(k,v){try{localStorage.setItem('triangle:'+k,v)}catch{}},remove(k){try{localStorage.removeItem('triangle:'+k)}catch{}}};
const drafts={get(k){try{return JSON.parse(sessionStorage.getItem('triangle:'+k))}catch{return null}},set(k,v){try{sessionStorage.setItem('triangle:'+k,JSON.stringify(v))}catch{}},remove(k){try{sessionStorage.removeItem('triangle:'+k)}catch{}}};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000)}
function safeError(e){const code=e?.code||'';if(code.includes('operation-not-allowed'))return 'Firebase에서 Authentication → 익명 로그인을 활성화해 주세요.';if(code.includes('permission')||String(e?.message).toLowerCase().includes('permission'))return '방이 이미 찼거나 만료되었을 수 있어요. 새 방에서도 같은 오류가 나면 제공한 DB 보안 규칙을 게시했는지 확인하세요.';if(code.includes('network'))return '연결할 수 없어요. 학교망에서 Firebase 접속이 가능한지 확인하세요.';if(code.includes('invalid-api-key'))return 'Firebase 웹앱의 apiKey를 다시 확인해 주세요.';return e?.message||'연결 중 문제가 생겼어요. 다시 시도해 주세요.';}
async function guarded(fn){if(busy)return;busy=true;updateControls();try{await fn()}catch(e){console.error(e);toast(safeError(e))}finally{busy=false;updateControls()}}
function parseConfig(text){let obj;if(typeof text==='object')obj=text;else{let source=text.trim();const start=source.indexOf('{'),end=source.lastIndexOf('}');if(start<0||end<start)throw Error('firebaseConfig의 중괄호 { ... } 부분을 붙여 넣어 주세요.');source=source.slice(start,end+1).replace(/^\s*\/\/.*$/gm,'').replace(/([,{]\s*)([A-Za-z_$][\w$]*)\s*:/g,'$1"$2":').replace(/'([^'\\]*(?:\\.[^'\\]*)*)'/g,(_,v)=>JSON.stringify(v.replace(/\\'/g,"'"))).replace(/,\s*([}\]])/g,'$1');obj=JSON.parse(source)}
 if(!obj||Array.isArray(obj))throw Error('웹앱 설정 객체가 필요합니다.');const out={};for(const key of ['apiKey','authDomain','databaseURL','projectId','storageBucket','messagingSenderId','appId'])if(typeof obj[key]==='string')out[key]=obj[key];
 for(const key of ['apiKey','projectId','databaseURL'])if(!out[key])throw Error(`${key} 항목이 없어요. Firebase 웹앱 설정과 Realtime Database 주소를 함께 넣어 주세요.`);
 const u=new URL(out.databaseURL);if(u.protocol!=='https:'||!(/\.(firebaseio\.com|firebasedatabase\.app)$/.test(u.hostname)))throw Error('databaseURL에는 Firebase Realtime Database의 HTTPS 주소를 넣어 주세요.');return out;
}
function configHash(c){return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(c)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decodeConfig(s){s=s.replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(s),c=>c.charCodeAt(0))))}
function sharedURL(code=''){const u=new URL(location.href);u.pathname=u.pathname.replace(/[^/]*$/,'');u.search=code?'?room='+encodeURIComponent(code):'';u.hash=config?'cfg='+configHash(config):'';return u.toString()}
function showConfig(){if(config){$('configInput').value=JSON.stringify(config,null,2);$('studentLink').value=sharedURL();$('connectionSummary').textContent='연결 정보가 준비됐어요. 방을 만들거나 입장해 보세요.';$('connectionSummary').classList.add('connected')}else{$('studentLink').value='';$('connectionSummary').textContent='실시간 대결을 위해 교사 설정이 필요해요.';$('connectionSummary').classList.remove('connected')}}
async function connect(){if(remote)return remote;if(connecting)return connecting;if(!config)throw Error('먼저 교사 설정에서 Firebase를 연결하거나, 선생님이 공유한 학생 접속 링크로 들어오세요.');
 connecting=(async()=>{const timeout=new Promise((_,reject)=>setTimeout(()=>reject(Error('Firebase 연결이 늦어지고 있어요. 인터넷 연결과 학교망을 확인한 후 다시 시도하세요.')),18000));
 const loaded=await Promise.race([Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js')]),timeout]);
 const [appSDK,authSDK,dbSDK]=loaded;const old=appSDK.getApps().find(a=>a.name==='triangle-duel');if(old)await appSDK.deleteApp(old);const app=appSDK.initializeApp(config,'triangle-duel'),auth=authSDK.getAuth(app);await authSDK.setPersistence(auth,authSDK.browserLocalPersistence);const cred=await authSDK.signInAnonymously(auth);const db=dbSDK.getDatabase(app);remote={...dbSDK,db,uid:cred.user.uid};stopConnected=remote.onValue(remote.ref(db,'.info/connected'),snap=>{network=snap.val()===true;updateControls();if(room&&!demo)renderStatus()});return remote;
 })();try{return await connecting}finally{connecting=null}
}
function randomInt(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}
function generateCode(){const chars='ABCDEFGHJKMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<8;i++)s+=chars[randomInt()%chars.length];return s}
function nickname(){const name=$('nickname').value.trim();if(!name)throw Error('나의 별명을 먼저 입력해 주세요.');prefs.set('name',name);return name}
function newRoom(uid,name,n){const now=Date.now();return {version:1,createdAt:now,expiresAt:now+6*3600000,host:{uid,name},config:{n,seed:randomInt()},log:'',game:{phase:'waiting',count:0,turn:0,starter:0,rpsRound:0}}}
async function createRoom(){const name=nickname(),r=await connect();for(let tries=0;tries<5;tries++){const code=generateCode(),ref=r.ref(r.db,'rooms/'+code);await r.get(ref);const base=newRoom(r.uid,name,Number($('pointCount').value));const tx=await r.runTransaction(ref,old=>old?undefined:base,{applyLocally:false});if(tx.committed){demo=false;roomCode=code;slot=0;await subscribe();return}}throw Error('방 코드 생성에 실패했어요. 다시 시도해 주세요.')}
async function joinRoom(){
 const code=$('roomInput').value.trim().toUpperCase();
 if(!/^[A-Z2-9]{8}$/.test(code))throw Error('8자리 방 코드를 확인해 주세요.');
 const name=nickname(),r=await connect(),ref=r.ref(r.db,'rooms/'+code);
 // Keep an active listener through the transaction. A one-shot get() does not
 // guarantee that RTDB's initial transaction callback has a cached room value.
 let stop=()=>{},timer;
 const ready=new Promise((resolve,reject)=>{
  timer=setTimeout(()=>reject(Error('방 정보를 아직 받지 못했어요. 인터넷 연결을 확인하고 다시 입장해 주세요.')),15000);
  stop=r.onValue(ref,resolve,reject);
 });
 try{
  const snap=await ready;clearTimeout(timer);
  if(!snap.exists())throw Error('해당 방이 없어요. 방 코드를 확인하세요.');
  const initial=snap.val();
  if(initial.expiresAt<Date.now())throw Error('만료된 방이에요. 새 방을 만들어 주세요.');
  let joined=initial;
  if(initial.host.uid!==r.uid&&initial.guest?.uid!==r.uid){
   if(initial.guest||initial.game.phase!=='waiting')throw Error('이미 두 사람이 참여한 방이에요.');
   let reason='방 상태가 바뀌었어요. 다시 입장해 주세요.';
   const tx=await r.runTransaction(ref,data=>{
    if(!data){reason='방 정보를 아직 받지 못했어요. 잠시 후 다시 입장해 주세요.';return;}
    if(data.expiresAt<Date.now()){reason='만료된 방이에요. 새 방을 만들어 주세요.';return;}
    if(data.host.uid===r.uid||data.guest?.uid===r.uid)return data;
    if(data.guest||data.game.phase!=='waiting'){reason='이미 두 사람이 참여한 방이에요.';return;}
    data.guest={uid:r.uid,name};data.game.phase='rps';return data;
   },{applyLocally:false});
   if(!tx.committed)throw Error(reason);
   joined=tx.snapshot.val();
  }
  demo=false;roomCode=code;slot=joined.host.uid===r.uid?0:1;
  await subscribe();
 }finally{clearTimeout(timer);stop();}
}
async function subscribe(){if(unsub)unsub();lastEffectCount=0;selected=[];const r=remote;$('home').hidden=true;$('match').hidden=false;history.replaceState(null,'',sharedURL(roomCode));drafts.set('resume',roomCode);unsub=r.onValue(r.ref(r.db,'rooms/'+roomCode),snap=>{if(!snap.exists()){toast('방이 닫혔어요. 새 방으로 다시 시작하세요.');resetMatch();return}void acceptRoom(snap.val())},err=>toast(safeError(err)));await attachPresence()}
async function attachPresence(){const r=remote,code=roomCode;const path=r.ref(r.db,`presence/${code}/${r.uid}`);if(unsubPresence)unsubPresence();unsubPresence=r.onValue(r.ref(r.db,'presence/'+code),snap=>{presence=snap.val()||{};renderStatus()});const stateRef=r.ref(r.db,'.info/connected');const off=r.onValue(stateRef,async snap=>{if(snap.val()&&roomCode===code&&!demo){try{await r.onDisconnect(path).set({online:false,lastSeen:r.serverTimestamp()});await r.set(path,{online:true,lastSeen:r.serverTimestamp()})}catch(e){console.error(e)}}});const previous=unsubPresence;unsubPresence=()=>{previous();off();void r.remove(path).catch(()=>{})}}
async function transact(fn){if(demo){const next=fn(JSON.parse(JSON.stringify(room)));if(!next)throw Error('현재 차례가 바뀌었어요. 다시 확인하세요.');await acceptRoom(next);return next}if(!network)throw Error('연결이 끊겼어요. 다시 연결될 때까지 기다려 주세요.');const r=remote;const tx=await r.runTransaction(r.ref(r.db,'rooms/'+roomCode),current=>current?fn(current):undefined,{applyLocally:false});if(!tx.committed)throw Error('상태가 바뀌었어요. 화면을 확인한 후 다시 선택해 주세요.');await acceptRoom(tx.snapshot.val());return tx.snapshot.val()}
async function hashHand(h,nonce,d=room){const bytes=new TextEncoder().encode(`${roomCode}|${d.config.seed}|${d.game.rpsRound}|${h}|${nonce}`);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function chooseHand(hand){if(!room||room.game.phase!=='rps')return;const player=demo?demoSlot:slot,round=room.game.rpsRound,key=`r${round}`,side=player===0?'h':'g';const prior=room.rps?.[key]?.[side];if(prior?.commit)return;
 const nonce=String(randomInt())+String(randomInt()),commit=await hashHand(hand,nonce);drafts.set(`${roomCode}:${round}:${side}`,{hand,nonce});await transact(d=>{if(d.game.phase!=='rps'||d.game.rpsRound!==round||d.rps?.[key]?.[side]?.commit)return;d.rps||={};d.rps[key]||={};d.rps[key][side]={commit};return d});if(demo){demoSlot=player===0?1:0;renderRps();void processRps()}}
async function verifyHands(d){const pair=d.rps?.['r'+d.game.rpsRound];if(!pair||pair.h?.hand===undefined||pair.g?.hand===undefined)return false;for(const side of ['h','g']){const v=pair[side];if(![0,1,2].includes(v.hand)||await hashHand(v.hand,v.nonce,d)!==v.commit)throw Error('가위바위보 기록이 맞지 않아요. 새 방을 만들어 주세요.')}return true}
async function processRps(){if(advancing||!room||room.game.phase!=='rps')return;advancing=true;try{const round=room.game.rpsRound,key='r'+round,pair=room.rps?.[key];if(!pair?.h?.commit||!pair?.g?.commit)return;
 for(const side of demo?['h','g']:[slot===0?'h':'g']){const own=room.rps?.[key]?.[side];if(own?.hand!==undefined)continue;const choice=drafts.get(`${roomCode}:${round}:${side}`);if(!choice){toast('가위바위보 선택 기록이 없어졌어요. 새 방에서 다시 시작하세요.');return}await transact(d=>{if(d.game.phase!=='rps'||d.game.rpsRound!==round||d.rps[key][side].hand!==undefined)return;d.rps[key][side]={...d.rps[key][side],hand:choice.hand,nonce:choice.nonce};return d})}
 if(await verifyHands(room)){const pair=room.rps[key],winner=handWinner(pair.h.hand,pair.g.hand);await transact(d=>{if(d.game.phase!=='rps'||d.game.rpsRound!==round||d.rps?.[key]?.h?.hand===undefined||d.rps?.[key]?.g?.hand===undefined)return;if(winner===-1){d.game.rpsRound++;}else{d.game.phase='playing';d.game.starter=winner;d.game.turn=winner}return d});if(winner===-1){demoSlot=0;toast(`둘 다 ${handNames[pair.h.hand]}! 다시 가위바위보를 해요.`)}else toast(`${winner===0?room.host.name:room.guest.name}부터 시작해요!`)}
 }catch(e){if(!String(e.message).includes('상태가 바뀌'))toast(safeError(e))}finally{advancing=false;const p=room?.rps?.['r'+room?.game.rpsRound];if(room?.game.phase==='rps'&&p?.h?.commit&&p?.g?.commit&&(!p.h.nonce||!p.g.nonce||p.h.hand!==undefined&&p.g.hand!==undefined))setTimeout(()=>void processRps(),100)}}
async function acceptRoom(d){const generation=++acceptVersion;try{if(!d||d.version!==1||![12,20,30].includes(d.config?.n)||!Number.isInteger(d.config.seed)||!['waiting','rps','playing'].includes(d.game.phase))throw Error('방 설정을 읽을 수 없어요. 새 방을 만들어 주세요.');if(d.expiresAt<Date.now()&&!demo)throw Error('방이 만료됐어요. 새 방으로 다시 시작하세요.');if(d.game.phase==='playing'){if(!await verifyHands(d))throw Error('가위바위보가 끝나지 않았어요.');const pair=d.rps['r'+d.game.rpsRound];if(handWinner(pair.h.hand,pair.g.hand)!==d.game.starter)throw Error('선공 기록이 올바르지 않아요.');}if(generation!==acceptVersion)return;const next=replay(d.config,d.log,d.game.starter);if(next.moves.length!==d.game.count||next.turn!==d.game.turn)throw Error('대결 순서가 올바르지 않아요. 새 방을 만들어 주세요.');room=d;model=next;if(selected.length&&selected.length===2&&legalReason(model.points,model.moves,...selected))selected=[];render();if(next.moves.length>lastEffectCount){const fresh=next.triangles.filter(t=>t.move>=lastEffectCount),sum=fresh.reduce((s,t)=>s+TYPES[t.type].points,0);if(fresh.length)effect(`${fresh.length>1?fresh.length+'개 완성!':'삼각형 완성!'} +${sum}점`)}lastEffectCount=next.moves.length;void processRps()}catch(e){console.error(e);toast(safeError(e));$('drawBtn').disabled=true}}
function startDemo(){resetMatch(false);demo=true;roomCode='체험';demoSlot=0;slot=0;lastEffectCount=0;const d=newRoom('demo-host','파랑',Number($('pointCount').value));d.guest={uid:'demo-guest',name:'주황'};d.game.phase='rps';$('home').hidden=true;$('match').hidden=false;void acceptRoom(d)}
function render(){if(!room||!model)return;$('modeLabel').textContent=demo?'한 기기에서 규칙 체험':'실시간 1 : 1 대결';$('roomBadge').textContent=demo?'체험 모드':'방 '+roomCode;$('copyInvite').hidden=demo;$('largeCode').textContent=roomCode;$('lobby').hidden=room.game.phase!=='waiting';$('rpsPanel').hidden=room.game.phase!=='rps';$('playSurface').hidden=room.game.phase!=='playing';$('result').hidden=room.game.phase!=='playing'||!model.finished;if(room.game.phase==='rps')renderRps();if(room.game.phase==='playing'){
 for(let p=0;p<2;p++){const name=p===0?room.host.name:room.guest.name;$('name'+p).textContent=name+(!demo&&p===slot?' (나)':'');$('score'+p).textContent=model.scores[p];$('player'+p).classList.toggle('active',model.turn===p&&!model.finished);$('counts'+p).textContent=`예각 ${model.counts[p].acute} · 직각 ${model.counts[p].right} · 둔각 ${model.counts[p].obtuse}`}
 $('triangleCount').textContent=model.triangles.length;renderBoard();renderTriangles();if(model.finished){const [a,b]=model.scores;$('winnerText').textContent=a===b?`무승부! ${a} : ${b}`:`${a>b?room.host.name:room.guest.name} 승리! ${a} : ${b}`}}
 renderStatus();updateControls()}
function renderRps(){const round=room.game.rpsRound,pair=room.rps?.['r'+round]||{},side=(demo?demoSlot:slot)===0?'h':'g',own=pair[side],other=pair[side==='h'?'g':'h'];$('rpsTitle').textContent=round?'다시 가위바위보!':'가위바위보!';$('rpsInfo').textContent=demo?`${demoSlot===0?'파랑':'주황'} 차례에 손 모양을 골라 주세요.`:'손 모양을 골라 주세요. 두 사람이 고르면 함께 공개해요.';$('rpsResult').textContent=own?.commit?'선택했어요. 친구의 선택을 기다려 주세요.':other?.commit?'친구가 선택했어요. 이제 나의 선택!':'';document.querySelectorAll('[data-hand]').forEach(b=>{b.disabled=busy||!!own?.commit;b.classList.remove('selected')})}
function renderStatus(){if(!room||!model)return;for(let p=0;p<2;p++){const uid=p===0?room.host.uid:room.guest?.uid;$('presence'+p).textContent=demo?'':presence[uid]?.online?'접속 중':'연결 기다림'}if(room.game.phase!=='playing')return;let text=model.finished?'놀이가 끝났어요.':demo?`${model.turn===0?room.host.name:room.guest.name} 차례`:model.turn===slot?'내 차례! 점 두 개를 선택하세요.':`${model.turn===0?room.host.name:room.guest.name} 차례를 기다려요.`;if(!demo&&!network)text='연결이 끊겼어요. 다시 연결될 때까지 기다려요.';$('turnText').textContent=text;$('turnText').style.color=colors[model.turn];$('moveCounter').textContent=`${model.moves.length}번째 선분 · 가능 ${model.remaining}개`}
const svgNS='http://www.w3.org/2000/svg';function svgEl(tag,attrs={},text){const e=document.createElementNS(svgNS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function renderBoard(){const svg=$('board');svg.replaceChildren();for(const t of model.triangles){const p=t.ids.map(i=>`${model.points[i].x},${model.points[i].y}`).join(' ');svg.append(svgEl('polygon',{points:p,fill:colors[t.p],'fill-opacity':'.13',stroke:'none'}))}model.moves.forEach((m,i)=>{const a=model.points[m.a],b=model.points[m.b];svg.append(svgEl('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:colors[m.p],'stroke-width':i===model.moves.length-1?4:3,'stroke-linecap':'round'}))});if(selected.length===2){const [a,b]=selected.map(i=>model.points[i]);svg.append(svgEl('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:colors[model.turn],'stroke-width':4,'stroke-dasharray':'8 7'}))}model.points.forEach((p,i)=>{const g=svgEl('g',{class:'dot-hit',tabindex:canPlay()?0:-1,role:'button','aria-label':`점 ${i+1}${selected.includes(i)?', 선택됨':''}`});g.append(svgEl('circle',{cx:p.x,cy:p.y,r:19,fill:'transparent',class:'halo'}));if(selected.includes(i))g.append(svgEl('circle',{cx:p.x,cy:p.y,r:14,fill:colors[model.turn],'fill-opacity':'.16',stroke:colors[model.turn],'stroke-width':2}));else if(selected.length===1&&!legalReason(model.points,model.moves,selected[0],i))g.append(svgEl('circle',{cx:p.x,cy:p.y,r:13,fill:'#e6f0ea'}));g.append(svgEl('circle',{cx:p.x,cy:p.y,r:selected.includes(i)?7:5,fill:selected.includes(i)?colors[model.turn]:'#264d42',class:'dot'}));g.addEventListener('click',()=>pickPoint(i));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pickPoint(i)}});svg.append(g)})}
function canPlay(){return !!room&&room.game.phase==='playing'&&!model?.finished&&(demo||network&&model.turn===slot)&&!busy}
function pickPoint(i){if(!canPlay()){if(!demo&&model?.turn!==slot)toast('지금은 친구 차례예요.');return}if(selected.includes(i))selected=selected.filter(x=>x!==i);else if(selected.length===1){const why=legalReason(model.points,model.moves,selected[0],i);if(why){toast(why);return}selected.push(i)}else selected=[i];renderBoard();updateControls();if(selected.length===1){const p=model.points[i];requestAnimationFrame(()=>{$('board').querySelector(`g[aria-label^="점 ${i+1},"]`)?.focus()})}}
function updateControls(){const valid=selected.length===2&&model&&!legalReason(model.points,model.moves,...selected);$('drawBtn').disabled=!valid||!canPlay();$('drawBtn').textContent=busy?'저장 중…':'선분 그리기';$('selectionText').textContent=selected.length===2?`점 ${selected[0]+1}과 ${selected[1]+1}을 이어 볼까요?`:selected.length===1?`점 ${selected[0]+1} 선택! 연결할 다른 점을 고르세요.`:'점 두 개를 차례로 선택하세요.';$('createBtn').disabled=busy;$('joinBtn').disabled=busy;$('saveConfig').disabled=busy;$('cancelSelection').disabled=busy||!selected.length;if(room?.game.phase==='rps')renderRps()}
async function draw(){if(!model||selected.length!==2)return;const [a,b]=selected,expected=model.moves.length,p=model.turn;await transact(d=>{if(d.game.phase!=='playing'||d.game.count!==expected||d.game.turn!==p||(!demo&&(p===0?d.host.uid:d.guest.uid)!==remote.uid))return;const current=replay(d.config,d.log,d.game.starter);if(legalReason(current.points,current.moves,a,b))return;d.log+=`${a},${b},${p};`;d.last={a,b,p};d.game.count++;d.game.turn=1-p;return d});selected=[];render()}
function effect(text){$('effect').textContent=text;$('effect').classList.add('show');clearTimeout(effectTimer);effectTimer=setTimeout(()=>$('effect').classList.remove('show'),2000)}
function renderTriangles(){const list=$('triangleList');list.replaceChildren();if(!model.triangles.length){const p=document.createElement('p');p.className='empty-note';p.textContent='아직 완성한 삼각형이 없어요. 세 변을 연결해 보세요.';list.append(p);return}model.triangles.forEach((t,i)=>{const b=document.createElement('button');b.className='triangle-chip '+(t.p?'orange':'blue');const label=document.createElement('span');label.textContent=`△ ${i+1} ${TYPES[t.type].name}`;const pts=document.createElement('b');pts.textContent=`+${TYPES[t.type].points}`;b.append(label,pts);b.onclick=()=>showTriangle(i);list.prepend(b)})}
function showTriangle(i){const t=model.triangles[i];if(!t)return;detailsIndex=i;const raw=t.ids.map(id=>model.points[id]),minX=Math.min(...raw.map(p=>p.x)),maxX=Math.max(...raw.map(p=>p.x)),minY=Math.min(...raw.map(p=>p.y)),maxY=Math.max(...raw.map(p=>p.y)),scale=Math.min(270/Math.max(1,maxX-minX),180/Math.max(1,maxY-minY)),cx=(minX+maxX)/2,cy=(minY+maxY)/2,pts=raw.map(p=>({x:200+(p.x-cx)*scale,y:145+(p.y-cy)*scale}));const svg=$('detailSvg');svg.replaceChildren(svgEl('polygon',{points:pts.map(p=>`${p.x},${p.y}`).join(' '),stroke:colors[t.p],'stroke-width':3,fill:colors[t.p],'fill-opacity':'.12'}));const deg=angles(model.points,t.ids);pts.forEach((p,j)=>{svg.append(svgEl('circle',{cx:p.x,cy:p.y,r:5,fill:colors[t.p]}));const center={x:pts.reduce((s,a)=>s+a.x,0)/3,y:pts.reduce((s,a)=>s+a.y,0)/3},vx=p.x-center.x,vy=p.y-center.y,d=Math.hypot(vx,vy);svg.append(svgEl('text',{x:p.x+vx/d*24,y:p.y+vy/d*24+5,'text-anchor':'middle','font-size':16,fill:'#28483d'},`${deg[j].toFixed(1)}°`))});$('detailTitle').textContent=`${i+1}번 ${TYPES[t.type].name} · ${TYPES[t.type].points}점`;$('detailExplanation').textContent=t.type==='acute'?'세 각이 모두 90°보다 작아서 예각삼각형이에요.':t.type==='right'?'한 각이 90°여서 직각삼각형이에요.':'한 각이 90°보다 커서 둔각삼각형이에요.';$('triangleDialog').showModal()}
function resetMatch(showHome=true){acceptVersion++;if(unsub){unsub();unsub=null}if(unsubPresence){unsubPresence();unsubPresence=null}room=null;model=null;roomCode='';demo=false;selected=[];presence={};detailsIndex=null;drafts.remove('resume');clearTimeout(effectTimer);$('effect').classList.remove('show');if(showHome){$('home').hidden=false;$('match').hidden=true;history.replaceState(null,'',sharedURL())}}
async function leave(){if(!demo&&room){const uid=remote.uid;if(room.host.uid===uid){if(!confirm(room.guest?'방을 닫으면 친구의 대결도 끝나요. 나갈까요?':'대결 방을 닫고 나갈까요?'))return;await remote.remove(remote.ref(remote.db,'rooms/'+roomCode))}else if(!confirm('대결에서 나갈까요? 방 코드를 입력하면 다시 입장할 수 있어요.'))return}resetMatch()}
async function copy(text){if(!text)throw Error('먼저 연결 설정을 저장해 주세요.');try{await navigator.clipboard.writeText(text);toast('링크를 복사했어요.')}catch{prompt('아래 링크를 복사하세요.',text)}}
$('createBtn').onclick=()=>guarded(createRoom);$('joinBtn').onclick=()=>guarded(joinRoom);$('demoBtn').onclick=startDemo;$('drawBtn').onclick=()=>guarded(draw);$('cancelSelection').onclick=()=>{selected=[];renderBoard();updateControls()};$('leaveBtn').onclick=()=>guarded(leave);$('newGameBtn').onclick=()=>guarded(leave);$('copyInvite').onclick=()=>guarded(()=>copy(sharedURL(roomCode)));$('copyStudentLink').onclick=()=>guarded(()=>copy($('studentLink').value));$('rulesBtn').onclick=()=>$('rulesDialog').showModal();$('setupBtn').onclick=()=>{if(room){toast('연결 설정은 대결에서 나온 뒤 변경할 수 있어요.');return}showConfig();$('setupDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('[data-hand]').forEach(b=>b.onclick=()=>guarded(()=>chooseHand(Number(b.dataset.hand))));
$('saveConfig').onclick=()=>guarded(async()=>{const next=parseConfig($('configInput').value);config=next;remote=null;if(stopConnected){stopConnected();stopConnected=null}prefs.set('config',JSON.stringify(config));showConfig();$('setupStatus').textContent='익명 인증과 DB 읽기·쓰기를 확인하고 있어요…';try{const r=await connect(),code=generateCode(),ref=r.ref(r.db,'rooms/'+code);await r.get(ref);const tx=await r.runTransaction(ref,old=>old?undefined:newRoom(r.uid,'연결확인',12),{applyLocally:false});if(!tx.committed)throw Error('연결 확인용 방을 생성하지 못했어요. 다시 시도하세요.');await r.remove(ref);$('setupStatus').textContent='연결 성공! 학생 접속 링크를 공유하고 두 기기에서 대결을 시작해 보세요.';$('connectionSummary').textContent='Firebase 연결 확인 완료 · 별명으로 참여해요.'}catch(e){$('setupStatus').textContent='확인 실패: '+safeError(e);throw e}});
$('clearConfig').onclick=()=>{if(stopConnected)stopConnected();stopConnected=null;remote=null;config=null;network=false;prefs.remove('config');$('configInput').value='';$('setupStatus').textContent='이 기기의 설정을 지웠어요.';history.replaceState(null,'',location.pathname);showConfig()};
try{const fragment=new URLSearchParams(location.hash.slice(1)).get('cfg');const saved=fragment?decodeConfig(fragment):window.TRIANGLE_FIREBASE_CONFIG||JSON.parse(prefs.get('config')||'null');if(saved){config=parseConfig(saved);prefs.set('config',JSON.stringify(config))}}catch(e){toast('연결 정보가 올바르지 않아요. 선생님이 공유한 링크를 다시 확인하세요.')}
$('nickname').value=prefs.get('name')||'';$('roomInput').value=new URLSearchParams(location.search).get('room')||'';showConfig();updateControls();
if(config&&drafts.get('resume')===$('roomInput').value&&$('nickname').value)void guarded(joinRoom);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_triangle_match',description:'현재 삼각형 대결의 차례, 점수, 남은 선분 수를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>room?{mode:demo?'demo':'online',phase:room.game.phase,turn:model.turn,scores:model.scores,triangles:model.triangles.length,remaining:model.remaining}:{phase:'home'}});document.modelContext.registerTool({name:'select_triangle_points',description:'내 차례에 선분의 두 끝점을 선택합니다. 선분을 그리지는 않습니다. 점 번호는 1부터 시작합니다.',inputSchema:{type:'object',properties:{a:{type:'integer',minimum:1},b:{type:'integer',minimum:1}},required:['a','b'],additionalProperties:false},execute:({a,b})=>{if(!canPlay())throw Error('현재 선분을 선택할 수 없습니다.');const why=legalReason(model.points,model.moves,a-1,b-1);if(why)throw Error(why);selected=[a-1,b-1];renderBoard();updateControls();return {selected:[a,b],ready:true}}})}catch(e){console.debug('WebMCP unavailable',e)}}
